# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 02:26
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0002_auto_20170116_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerprofile',
            name='imager_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
