# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 02:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0003_imagerprofile_imager_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagerprofile',
            name='is_active',
        ),
    ]
