# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0004_remove_imagerprofile_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='bio',
            field=models.TextField(default=''),
        ),
    ]
