# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 03:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imager_profile', '0005_auto_20170117_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_published', models.DateTimeField()),
                ('published', models.SmallIntegerField(choices=[(1, 'Private'), (2, 'Shared'), (3, 'Public')], default=1, max_length=2)),
                ('cover', models.ImageField(upload_to='images')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imager_profile.ImagerProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('date_uploaded', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('date_published', models.DateTimeField()),
                ('published', models.SmallIntegerField(choices=[(1, 'Private'), (2, 'Shared'), (3, 'Public')], default=1, max_length=2)),
                ('image', models.ImageField(upload_to='images')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imager_profile.ImagerProfile')),
            ],
        ),
    ]
