# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 17:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0003_auto_20170122_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='cover',
            new_name='cover_image',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='image',
            new_name='image_file',
        ),
    ]
