# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 01:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0008_auto_20170123_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='photos',
            new_name='images',
        ),
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(upload_to='MEDIA/images/cover_photos'),
        ),
        migrations.AlterField(
            model_name='album',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album', to='imager_profile.ImagerProfile'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_file',
            field=models.ImageField(upload_to='MEDIA/images'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='imager_profile.ImagerProfile'),
        ),
    ]
