# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 03:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0010_auto_20170124_2310'),
        ('imager_images', '0011_auto_20170124_1932'),
    ]

    operations = [
    ]
