# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0012_merge_20170125_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='user_id',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='user_id',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='album',
            name='published',
            field=models.CharField(choices=[('private', 'Private'), ('shared', 'Shared'), ('public', 'Public')], default='private', max_length=15),
        ),
        migrations.AlterField(
            model_name='photo',
            name='published',
            field=models.CharField(choices=[('private', 'Private'), ('shared', 'Shared'), ('public', 'Public')], default='private', max_length=15),
        ),
    ]
